// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApi.Model;

#nullable disable

namespace MinimalApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230804165133_prova")]
    partial class prova
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("MinimalApi.Model.NEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("utenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("utenteId");

                    b.ToTable("nmail");
                });

            modelBuilder.Entity("MinimalApi.Model.NTelefono", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("utenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("utenteId");

                    b.ToTable("ntelefono");
                });

            modelBuilder.Entity("MinimalApi.Model.Utente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("indirizzo")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("utente");
                });

            modelBuilder.Entity("MinimalApi.Model.NEmail", b =>
                {
                    b.HasOne("MinimalApi.Model.Utente", null)
                        .WithMany("emails")
                        .HasForeignKey("utenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinimalApi.Model.NTelefono", b =>
                {
                    b.HasOne("MinimalApi.Model.Utente", null)
                        .WithMany("telefoni")
                        .HasForeignKey("utenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinimalApi.Model.Utente", b =>
                {
                    b.Navigation("emails");

                    b.Navigation("telefoni");
                });
#pragma warning restore 612, 618
        }
    }
}
